global:
  resolve_timeout: 5m
  # slack_api_url: 'YOUR_SLACK_WEBHOOK_URL' # Example for Slack
  # smtp_smarthost: 'localhost:25'
  # smtp_from: 'alertmanager@example.com'

route:
  receiver: 'default-receiver'
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h # How long to wait before re-firing an alert that has already been sent.

  # A default receiver
receivers:
  - name: 'default-receiver'
    # email_configs:
    #   - to: 'your-email@example.com'
    # slack_configs:
    #   - channel: '#alerts-poker-helper'
    #     send_resolved: true

# Inhibition rules (optional, to prevent flapping or related alerts)
# inhibit_rules:
#   - source_match:
#       severity: 'critical'
#     target_match:
#       severity: 'warning'
#     # Apply inhibition if the alertname is the same.
#     equal: ['alertname', 'job']
